# Generated by Django 6.0.2 on 2026-02-21 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='Cateqory',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='webapp.cateqory'),
            preserve_default=False,
        ),
    ]
