# Generated by Django 6.0.2 on 2026-02-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_record_cateqory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
